### ISSUE TITLE
Search functionality is broken

### ISSUE THREAD

**Issue by mewfree** [valeriangalliat/blog#8]
When looking at the `console.log`, I can see that you're attempting to use GitHub's Code Search API, but a 401 Unauthorized is received.

Indeed, since April 2023, all GitHub Code Search API requests must be authenticated: https://github.blog/changelog/2023-03-10-changes-to-the-code-search-api/

**Comment by valeriangalliat** [comment]
Thanks! Had to move to using a Vercel function to call the GitHub API with a token
